services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: prevent:dev
    volumes:
      - ./src:/app/src:Z
    environment:
      DASH_DEBUG: true
      TC_LOGLEVEL: debug
      TC_DEBUG: true
  terracotta:
    environment:
      TC_LOGLEVEL: debug
      TC_DEBUG: true