FROM python:3.12-slim

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY . /app
RUN pip install -U pip \
    && pip install -e .

# Expose the port the app runs on
EXPOSE 8050

# Command to run the app
CMD ["gunicorn", "recall.dapp:server", "-b", "0.0.0.0:8050", "--reload"]
