version: '3.8'
services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: preventdb
      POSTGRES_USER: preventuser
      POSTGRES_PASSWORD: kukkakaalisinappi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: